### ISSUE TITLE
Initial endpoint for loan statistics

### ISSUE THREAD

**Issue by skyripley** [Skyblueballykid/kiva-crowd#13]
We need to build an endpoint that will support our loan statistics view. For this issue we can aim to return general statistics with no filtering. Part of this ticket should also be deciding what statistics we return and updating the team with this decision.

Resources:
- https://docs.djangoproject.com/en/3.0/topics/db/sql/
  - These statistics should be gathered via raw sql rather than the orm so that we can show our TAs when we submit the project

Acceptance criteria:
- Initial endpoint to return loan statistics
  - Queries should be in raw sql and not use the orm
- Statistics to be returned should be decided

**Comment by Skyblueballykid** [comment]
Ideas for statistics using raw SQL queries:
- Average loan amount 
- Average loan amount by country, limit 5
- Count of loans by country limit 5
- Average loan amount by Sector_Name
- Loan count by Activity_Name, limit 5

**Comment by nitish7892** [comment]
Done and pushed to dev.
