### ISSUE TITLE
Upload dataset to postgres container on Lightsail

### ISSUE THREAD

**Issue by skyripley** [Skyblueballykid/kiva-crowd#17]
We have our Lightsail infrastructure mostly setup, but we need to upload the kiva dataset to the db running in our `postgres` container.

Resources:
- Dataset - https://www.kiva.org/build/data-snapshots
- https://dbeaver.io/ (recommended by @ntt2k as a good postgres client)

Acceptance criteria:
- Dataset (or sample of dataset) uploaded to db
  - If sample is created please upload sample to somewhere like s3 as well so that we do not need to create the sample more than once. Having this stored somewhere where everyone can access it will make local development easier so that we're not all having to create our own sample for dev

**Comment by ntt2k** [comment]
Done in PR:
https://github.com/Skyblueballykid/kiva-crowd/pull/26
https://github.com/Skyblueballykid/kiva-crowd/pull/28
