### ISSUE TITLE
Paginate get loans endpoint

### ISSUE THREAD

**Issue by skyripley** [Skyblueballykid/kiva-crowd#3]
Looks like the `GET /loans` endpoint is pretty much built already, but we should paginate the results so that we're not retuning too much to the frontend. No filters or search functionality should be added here - those should come in a later ticket. See https://docs.djangoproject.com/en/3.0/topics/pagination/ for details on pagination in Django.

Acceptance Criteria:
- `GET /loans` endpoint modified to support pagination

**Comment by ntt2k** [comment]
@skyripley the code base use djangorestframework library ... the GET loans list endpoint has already built with pagination

<img width="780" alt="Screen Shot 2020-03-09 at 6 00 40 PM" src="https://user-images.githubusercontent.com/4227421/76264471-ea2ca200-622f-11ea-826c-9cc1509410bf.png">

**Comment by skyripley** [comment]
Ah perfect! Closing this then @ntt2k
