### ISSUE TITLE
Setup frontend

### ISSUE THREAD

**Issue by skyripley** [Skyblueballykid/kiva-crowd#4]
We have the backend for our project setup, but we also need to setup all of the libraries, tooling, etc. for our frontend. We decided on using React so this issue should encompass everything needed to get this running. There are lots of tutorials that can probably help with this like https://www.valentinog.com/blog/drf/. As a result of this ticket we shouldn't have much built on the frontend, but we should have everything installed, instructions for local development, and we should be able to connect to the backend.

Resources:
- https://mherman.org/blog/dockerizing-a-react-app/
- https://medium.com/greedygame-engineering/so-you-want-to-dockerize-your-react-app-64fbbb74c217

Acceptance Criteria:
- Everything setup for our React frontend
  - Readme updated to include local dev instructions
  - Should be able to connect to backend
- Dockerfile should be included
- Service should be added to existing `docker-compose.yml`

**Comment by Skyblueballykid** [comment]
I'd like to give this a shot. I'll wait until you guys review the Dockerfile I pushed for Django.

**Comment by skyripley** [comment]
@Skyblueballykid I took a first shot at this in #16 since I figured this is a major blocker for us to move forward on frontend development. Definitely open to collaborating on this though since I have 0 react experience - feel free to add feedback to the PR and let me know if you're able to build/run the frontend without any major issues
