### ISSUE TITLE
Endpoint for text search

### ISSUE THREAD

**Issue by skyripley** [Skyblueballykid/kiva-crowd#8]
We need to create an endpoint that will support our full text search functionality. For this ticket we should aim to have very rough full-text search implemented in an endpoint. This can either be a modification to the `GET /loans` endpoint or it can be an entirely new endpoint, but we should have something very basic that our frontend can interact with so that it is unblocked.

Resources:
- https://docs.djangoproject.com/en/3.0/topics/db/sql/
  - We'll need to point our TAs to our queries so we should probably implement this with raw sql
- https://www.postgresql.org/docs/9.5/textsearch.html

Acceptance Criteria:
- Initial endpoint for full-text search built
  - Doesn't need to be perfect, but should provide something that our frontend can interact with so that the frontend isn't blocked until the full-text search is done

**Comment by Skyblueballykid** [comment]
I'd like to be involved with this issue.

**Comment by Skyblueballykid** [comment]
Skylar did this.
