### ISSUE TITLE
Full text search view

### ISSUE THREAD

**Issue by skyripley** [Skyblueballykid/kiva-crowd#9]
After we have a very rough first version of our text search endpoint we can go ahead and build the view that will allow users to interact with it. This can be a modification to an existing view like the table view or an entirely new view, but the goal is to have a text search box that users can interact with.

Acceptance Criteria:
- Text search view implemented
  - Can be a modification to an existing view or an entirely new view
  - Should call the endpoint built in #8

**Comment by Skyblueballykid** [comment]
All set.
